PYTHONINC = -I/usr/licensed/anaconda3/2021.11/include/python3.9/
NUMPYINC = -I/usr/licensed/anaconda3/2021.11/lib/python3.9/site-packages/numpy/core/include/
#PYTHONINC = -I/home/fanc/anaconda3/include/python3.8
#NUMPYINC = -I/home/fanc/anaconda3/lib/python3.8/site-packages/numpy/core/include
